import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, readFileSync, writeFileSync, rmSync, existsSync, cpSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { StdioClientTransport } from '@modelcontextprotocol/sdk/client/stdio.js';
import { writePackage } from '../scripts/package.mjs';
import { evidenceArgs } from './evidence-fixture.mjs';

// Exercise the actual relocated bundle with all outbound network denied, not source modules.
test('self-contained local package works with networking denied', { timeout: 120000 }, async (t) => {
  const temporary = mkdtempSync(path.join(tmpdir(), 'aas local '));
  t.after(() => rmSync(temporary, { recursive: true, force: true }));
  const plugin = path.join(temporary, 'plugin with spaces');
  if (process.env.AAS_TEST_PLUGIN_ROOT) cpSync(process.env.AAS_TEST_PLUGIN_ROOT, plugin, { recursive: true });
  const verified = process.env.AAS_TEST_PLUGIN_ROOT ? { skillCount: JSON.parse(readFileSync(path.join(plugin, 'core/data/catalog.json'), 'utf8')).skills.length } : await writePackage(plugin);
  assert.ok(verified.skillCount > 2600);
  assert.equal(existsSync(path.join(plugin, 'node_modules')), false);
  const config = JSON.parse(readFileSync(path.join(plugin, 'mcp.json'), 'utf8')).mcpServers.aas;
  assert.equal(config.type, 'stdio');
  assert.equal(config.command, 'node');
  assert.equal(config.url, undefined);
  assert.match(readFileSync(path.join(plugin, 'THIRD-PARTY-NOTICES.txt'), 'utf8'), /modelcontextprotocol/);
  const guard = path.join(temporary, 'deny-network.cjs');
  writeFileSync(guard, `const deny=()=>{throw new Error('NETWORK FORBIDDEN');}; globalThis.fetch=deny; for(const name of ['http','https']) {const m=require(name);m.request=deny;m.get=deny;} const net=require('net');net.Socket.prototype.connect=deny;net.Server.prototype.listen=deny;require('dns').lookup=deny;`);
  const env = { PATH: process.env.PATH, HOME: temporary, NODE_OPTIONS: `--require "${guard}"` };
  const clients = [];
  t.after(async () => { for (const client of clients) await client.close(); });
  async function connect() {
    const client = new Client({ name: 'aas-offline-test', version: '1.0.0' }, { capabilities: {} });
    clients.push(client);
    await client.connect(new StdioClientTransport({ command: process.execPath, args: [path.join(plugin, 'runtime/aas-mcp.cjs'), path.join(plugin, 'core')], cwd: temporary, env }));
    return client;
  }
  const client = await connect();
  const tools = await client.listTools();
  assert.equal(tools.tools.length, 10);
  const call = (name, args = {}) => client.callTool({ name, arguments: args });
  const search = await call('search_skills', { query: 'debugging', limit: 5 });
  assert.equal(search.isError, false);
  assert.ok(search.structuredContent.results.length);
  const nested = await call('get_skill', { id: '2d-games', includeContent: true });
  assert.equal(nested.isError, false);
  const inventory = await call('list_skill_files', { id: 'debugging-strategies' });
  assert.equal(inventory.isError, false);
  const file = await call('read_skill_file', { id: 'debugging-strategies', path: 'SKILL.md' });
  assert.equal(file.isError, false);
  const missing = await call('get_skill', { id: 'not-a-real-skill' });
  assert.equal(missing.isError, true);
  const traversal = await call('read_skill_file', { id: 'debugging-strategies', path: '../package.json' });
  assert.equal(traversal.isError, true);
  const composition = await call('compose_stack', { name: 'offline-test', targets: [{ host: 'codex', scope: 'project' }], profile: { goals: ['debugging'] }, skillIds: ['debugging-strategies'] });
  assert.equal(composition.isError, false);
  const manifest = composition.structuredContent.manifest;
  assert.deepEqual(manifest.skills.map((skill) => skill.id), ['debugging-strategies']);
  const inspection = await call('inspect_stack', { manifest });
  assert.equal(inspection.isError, false);
  const exported = await call('export_selection_evidence', evidenceArgs(inspection.structuredContent.manifestDigest));
  assert.equal(exported.isError, false, JSON.stringify(exported));
  const evidence = exported.structuredContent.evidence;
  const inspectedEvidence = await call('inspect_selection_evidence', { manifest, evidence });
  assert.equal(inspectedEvidence.isError, false);
  const workbench = await call('open_workbench');
  assert.deepEqual(workbench.structuredContent.manifest, manifest);
  assert.deepEqual(workbench.structuredContent.evidence, evidence);
  assert.ok(existsSync(workbench.structuredContent.localWorkbenchPath));
  const ui = await client.readResource({ uri: 'ui://aas/workbench-v1.html' });
  assert.deepEqual(ui.contents[0]._meta.ui.csp, { connectDomains: [], resourceDomains: [] });
  assert.ok(ui.contents[0].text.length > 100000);
  const isolated = await connect();
  const empty = await isolated.callTool({ name: 'open_workbench', arguments: {} });
  assert.equal(empty.structuredContent.manifest, undefined);
  const manifestFile = path.join(temporary, 'stack.json');
  const evidenceFile = path.join(temporary, 'evidence.json');
  const planFile = path.join(temporary, 'plan.json');
  writeFileSync(manifestFile, JSON.stringify(manifest));
  writeFileSync(evidenceFile, JSON.stringify(evidence));
  const cliPath = path.join(plugin, 'runtime/aas-core.cjs');
  const plan = spawnSync(process.execPath, [cliPath, 'stack', 'plan', '--manifest', manifestFile, '--target-root', temporary, '--out', planFile], { cwd: temporary, env, encoding: 'utf8' });
  assert.equal(plan.status, 0, plan.stderr);
  assert.equal(JSON.parse(plan.stdout).status, 'planned');
  const audit = spawnSync(process.execPath, [cliPath, 'stack', 'audit', '--manifest', manifestFile, '--evidence', evidenceFile, '--plan', planFile], { cwd: temporary, env, encoding: 'utf8' });
  assert.equal(audit.status, 0, audit.stderr);
  assert.equal(JSON.parse(audit.stdout).status, 'consistent');
  const denied = spawnSync(process.execPath, [path.join(plugin, 'runtime/aas-core.cjs'), 'catalog', 'update'], { cwd: temporary, env, encoding: 'utf8' });
  assert.equal(denied.status, 2);
  assert.match(denied.stderr, /offline/);
});
